export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";
export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";

export const ORDER_CREATED_SUCCESS = "ORDER_CREATED_SUCCESS";
export const ORDER_CREATED_FAIL = "ORDER_CREATED_FAIL";
export const ORDER_CREATED_REQUEST = "ORDER_CREATED_REQUEST";
